language: node_js
node_js: '8'
branches:
  only:
  - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: master
